### PR TITLE
The Origin of SQL Queries: Add Python SQLAlchemy/Flask example

### PR DESCRIPTION
**Pull request by tchollingsworth**

### CODE REVIEW

**Comment by ankane** [comment]
Hey @tchollingsworth, thanks for the PR 👍 I think it'll be a bit cleaner if the code doesn't need to rescue exceptions.

**Comment by tchollingsworth** [comment]
I did it that way because of the Python mantra _[It's easier to ask forgiveness than it is to get permission.](https://docs.python.org/3.4/glossary.html#term-eafp)_

They look almost the same to me so personally I have no preference either way, though.

```python
from flask import current_app, request, has_application_context,  \
                  has_request_context
from sqlalchemy.engine import Engine
from sqlalchemy import event

@event.listens_for(Engine, "before_cursor_execute", retval=True)
def annotate_queries(conn, cursor, statement, parameters, context, executemany):
    if has_application_context():
        if has_request_context():
            comment = " /* application:{},endpoint:{} */".format(current_app.name,
                                                                 request.endpoint)
            statement = statement + comment
        else:
            comment = " /* application:{} */".format(current_app.name)
            statement = statement + comment
    return statement, parameters
```

Happy to update the PR if you still disagree with Grace Hopper and Guido van Rossum.  :-)

**Comment by ankane** [comment]
Thanks for the info. I didn't realize it was a Python pattern. In this case, it feels like catching `RuntimeError` can mask other issues in the code.

**Comment by tchollingsworth** [comment]
Yeah RuntimeError is a really poor choice on Flask/Werkzeug's part, but it's their own fault if they overload it too much.  (This exception is reserved for user code and won't be thrown by the standard library or anything.)

**Pull request merged**
